### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Ihtml**
修改display: none 的作用说明

### CODE REVIEW

**Comment by Ihtml** [comment]
修改display:none的说明为：元素不显示，并从文档流中移除。

**Comment by dai08170** [comment]
Do not send this Email Again !!!

**Comment by sfilata** [comment]
Why I always receive this email?

**Comment by LeeLoveGem** [comment]
Because you pay attention, every time you have dynamic, you will receive the mail.

**Pull request merged**
